server {
    listen 80;
    server_name localhost;

    # BLOQUE BACKEND (NestJS)
    # ==========================================
    location /api/ {
        rewrite ^/api/(.*) /$1 break;
        proxy_pass http://backend_prod:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # BLOQUE FRONTEND (Vue Estático)
    # ==========================================
    location / {
        # Va por nginx, no vite
        proxy_pass http://frontend_prod:8080;
        
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        
        # En producción eliminamos las cabeceras de WebSockets 
        # porque ya no hay Hot-Reload.
    }
}