# Contraseñas encriptadas en Base64 (DB_PASSWORD, JWT_SECRET)
apiVersion: v1
kind: Secret
metadata: 
  name: backend-secret
  namespace: proyecto-tfg-2026
type: Opaque # Tipo para que podamos elegir libremente los secrets que queramos
data: 
  DB_USER: "cm9va2llczIwMjZfYWRtaW5fZGV2"
  DB_PASSWORD: "R1JfUm9va2llc18yMDI2IQ=="
  JWT_SECRET: ""